### ISSUE TITLE
'reqhb' command not valid

### ISSUE THREAD

**Issue by K4KDR** [ASU-cubesat/phxsat-gsw-public#3]
The website (http://phxcubesat.asu.edu/content/amateur-operations) lists TWO commands for us to utilize in this application:

`ping 2`

 -and-

`reqhb`

... reqhb returns "`Unrecognized command`".

I see in /src/cli.c that the ONLY two valid commands currently are 'ping' & 'quit'.  

Will there be updates to add more commands such as reqhb?

Thanks very much for the work done so far and of course for all the information that has been provided about the project online!

-Scott,  K4KDR

**Comment by sarahsrogers** [comment]
Hi, Scott,

Thanks for bringing this up. We were going to release the reqhb command but decided not to,  since this would have given amateur operators the functionality to send other proprietary commands to the satellite. I had forgotten that we decided not to release this command when I listed it on our website, so I'll make a point to correct that. 

However, the ping command essentially operates the same way as the reqhb command in that it allows operators to confirm 2 way communication with the satellite and verify when it is overhead if they don't want to wait the 30 seconds between heartbeats. 

We'll add the audio file of the ping command shortly so that you can test this with your setup. 

~Sarah

**Comment by sarahsrogers** [comment]
I've removed this from our website, so I'll go ahead and close this out.
